version: '3'

services:
    php:
        build: ./ # 構築時のオプションを指定、今回はDockerfileの場所
        volumes:
            - ./src:/var/www/html
        ports:
            - 8000:80
        container_name: php8.1-trial2
    mysql:
        platform: linux/x86_64 #Mac M1
        image: mysql:5.7
        volumes:
            - db-volume:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
        ports:
            - "3306:3306"
        container_name: mysql5.7-trial2

volumes:
    db-volume: